---
language: node_js
node_js:
  - "7"

cache:
  yarn: true

install:
  - yarn install
  - yarn global add bower
  - bower install

before_script: 
    - openssl aes-256-cbc -d -in key.pem.enc -out key.pem -k $ENC_KEY

script: 
  - if [ "$TRAVIS_BRANCH" == "production" ]; then
      bash ./deployToProduction.sh;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      bash ./deployToStaging.sh;
    fi

group:
  - "stable"

dist:
  - "precise"

os:
  - "linux"
