---
language: node_js
node_js:
  - "7"

cache:
  yarn: true

install:
  - yarn install
  - yarn global add bower
  - bower install

before_script: 
    - openssl aes-256-cbc -d -in key.pem.enc -out key.pem -k $ENC_KEY

production
  script:
    - bash ./deployToProduction.sh

master
  script:
    - bash ./deployToStaging.sh
